/* automatically generated by rust-bindgen 0.73.2 */

pub const PYLON_INFINITE: u32 = 4294967295;
pub const PYLON_PIXEL_TYPE_UNDEFINED: u32 = 4294967295;
pub const PYLON_PIXEL_TYPE_MONO1_PACKED: u32 = 2164326412;
pub const PYLON_PIXEL_TYPE_MONO2_PACKED: u32 = 2164391949;
pub const PYLON_PIXEL_TYPE_MONO4_PACKED: u32 = 2164523022;
pub const PYLON_PIXEL_TYPE_MONO8: u32 = 17301505;
pub const PYLON_PIXEL_TYPE_MONO8_SIGNED: u32 = 17301506;
pub const PYLON_PIXEL_TYPE_MONO10: u32 = 17825795;
pub const PYLON_PIXEL_TYPE_MONO10_PACKED: u32 = 17563652;
pub const PYLON_PIXEL_TYPE_MONO10P: u32 = 17432646;
pub const PYLON_PIXEL_TYPE_MONO12: u32 = 17825797;
pub const PYLON_PIXEL_TYPE_MONO12_PACKED: u32 = 17563654;
pub const PYLON_PIXEL_TYPE_MONO12P: u32 = 17563719;
pub const PYLON_PIXEL_TYPE_MONO16: u32 = 17825799;
pub const PYLON_PIXEL_TYPE_BAYER_GR8: u32 = 17301512;
pub const PYLON_PIXEL_TYPE_BAYER_RG8: u32 = 17301513;
pub const PYLON_PIXEL_TYPE_BAYER_GB8: u32 = 17301514;
pub const PYLON_PIXEL_TYPE_BAYER_BG8: u32 = 17301515;
pub const PYLON_PIXEL_TYPE_BAYER_GR10: u32 = 17825804;
pub const PYLON_PIXEL_TYPE_BAYER_RG10: u32 = 17825805;
pub const PYLON_PIXEL_TYPE_BAYER_GB10: u32 = 17825806;
pub const PYLON_PIXEL_TYPE_BAYER_BG10: u32 = 17825807;
pub const PYLON_PIXEL_TYPE_BAYER_GR12: u32 = 17825808;
pub const PYLON_PIXEL_TYPE_BAYER_RG12: u32 = 17825809;
pub const PYLON_PIXEL_TYPE_BAYER_GB12: u32 = 17825810;
pub const PYLON_PIXEL_TYPE_BAYER_BG12: u32 = 17825811;
pub const PYLON_PIXEL_TYPE_BAYER_GR12_PACKED: u32 = 17563690;
pub const PYLON_PIXEL_TYPE_BAYER_RG12_PACKED: u32 = 17563691;
pub const PYLON_PIXEL_TYPE_BAYER_GB12_PACKED: u32 = 17563692;
pub const PYLON_PIXEL_TYPE_BAYER_BG12_PACKED: u32 = 17563693;
pub const PYLON_PIXEL_TYPE_BAYER_GR10P: u32 = 17432662;
pub const PYLON_PIXEL_TYPE_BAYER_RG10P: u32 = 17432664;
pub const PYLON_PIXEL_TYPE_BAYER_GB10P: u32 = 17432660;
pub const PYLON_PIXEL_TYPE_BAYER_BG10P: u32 = 17432658;
pub const PYLON_PIXEL_TYPE_BAYER_GR12P: u32 = 17563735;
pub const PYLON_PIXEL_TYPE_BAYER_RG12P: u32 = 17563737;
pub const PYLON_PIXEL_TYPE_BAYER_GB12P: u32 = 17563733;
pub const PYLON_PIXEL_TYPE_BAYER_BG12P: u32 = 17563731;
pub const PYLON_PIXEL_TYPE_BAYER_GR16: u32 = 17825838;
pub const PYLON_PIXEL_TYPE_BAYER_RG16: u32 = 17825839;
pub const PYLON_PIXEL_TYPE_BAYER_GB16: u32 = 17825840;
pub const PYLON_PIXEL_TYPE_BAYER_BG16: u32 = 17825841;
pub const PYLON_PIXEL_TYPE_RGB8_PACKED: u32 = 35127316;
pub const PYLON_PIXEL_TYPE_BGR8_PACKED: u32 = 35127317;
pub const PYLON_PIXEL_TYPE_RGBA8_PACKED: u32 = 35651606;
pub const PYLON_PIXEL_TYPE_BGRA8_PACKED: u32 = 35651607;
pub const PYLON_PIXEL_TYPE_RGB10_PACKED: u32 = 36700184;
pub const PYLON_PIXEL_TYPE_BGR10_PACKED: u32 = 36700185;
pub const PYLON_PIXEL_TYPE_RGB12_PACKED: u32 = 36700186;
pub const PYLON_PIXEL_TYPE_BGR12_PACKED: u32 = 36700187;
pub const PYLON_PIXEL_TYPE_RGB16_PACKED: u32 = 36700211;
pub const PYLON_PIXEL_TYPE_BGR10V1_PACKED: u32 = 35651612;
pub const PYLON_PIXEL_TYPE_BGR10V2_PACKED: u32 = 35651613;
pub const PYLON_PIXEL_TYPE_RGB12V1_PACKED: u32 = 35913780;
pub const PYLON_PIXEL_TYPE_RGB8_PLANAR: u32 = 35127329;
pub const PYLON_PIXEL_TYPE_RGB10_PLANAR: u32 = 36700194;
pub const PYLON_PIXEL_TYPE_RGB12_PLANAR: u32 = 36700195;
pub const PYLON_PIXEL_TYPE_RGB16_PLANAR: u32 = 36700196;
pub const PYLON_PIXEL_TYPE_YUV411_PACKED: u32 = 34340894;
pub const PYLON_PIXEL_TYPE_YUV422_PACKED: u32 = 34603039;
pub const PYLON_PIXEL_TYPE_YUV444_PACKED: u32 = 35127328;
pub const PYLON_PIXEL_TYPE_YUV422_YUYV_PACKED: u32 = 34603058;
pub const PYLON_PIXEL_TYPE_YUV444_PLANAR: u32 = 2182611012;
pub const PYLON_PIXEL_TYPE_YUV422_PLANAR: u32 = 2182086722;
pub const PYLON_PIXEL_TYPE_YUV420_PLANAR: u32 = 2181824576;
pub const PYLON_PIXEL_TYPE_YCBCR420_8_YY_CBCR_SEMIPLANAR: u32 = 34341138;
pub const PYLON_PIXEL_TYPE_YCBCR422_8_YY_CBCR_SEMIPLANAR: u32 = 34603283;
pub const PYLON_PIXEL_TYPE_BICOLOR_RGBG8: u32 = 34603173;
pub const PYLON_PIXEL_TYPE_BICOLOR_BGRG8: u32 = 34603174;
pub const PYLON_PIXEL_TYPE_BICOLOR_RGBG10: u32 = 35651751;
pub const PYLON_PIXEL_TYPE_BICOLOR_RGBG10P: u32 = 34865320;
pub const PYLON_PIXEL_TYPE_BICOLOR_BGRG10: u32 = 35651753;
pub const PYLON_PIXEL_TYPE_BICOLOR_BGRG10P: u32 = 34865322;
pub const PYLON_PIXEL_TYPE_BICOLOR_RGBG12: u32 = 35651755;
pub const PYLON_PIXEL_TYPE_BICOLOR_RGBG12P: u32 = 35127468;
pub const PYLON_PIXEL_TYPE_BICOLOR_BGRG12: u32 = 35651757;
pub const PYLON_PIXEL_TYPE_BICOLOR_BGRG12P: u32 = 35127470;
pub const PYLON_PIXEL_TYPE_DOUBLE: u32 = 2168455424;
pub const PYLON_PIXEL_TYPE_CONFIDENCE8: u32 = 17301702;
pub const PYLON_PIXEL_TYPE_CONFIDENCE16: u32 = 17825991;
pub const PYLON_PIXEL_TYPE_COORD3D_C8: u32 = 17301681;
pub const PYLON_PIXEL_TYPE_COORD3D_C16: u32 = 17825976;
pub const PYLON_PIXEL_TYPE_COORD3D_ABC32F: u32 = 39846080;
pub const PYLON_PIXEL_TYPE_ERROR8: u32 = 2164785153;
pub const PYLON_PIXEL_TYPE_DATA8: u32 = 17301782;
pub const PYLON_PIXEL_TYPE_DATA8S: u32 = 17301783;
pub const PYLON_PIXEL_TYPE_DATA16: u32 = 17826072;
pub const PYLON_PIXEL_TYPE_DATA16S: u32 = 17826073;
pub const PYLON_PIXEL_TYPE_DATA32: u32 = 18874650;
pub const PYLON_PIXEL_TYPE_DATA32S: u32 = 18874651;
pub const PYLON_PIXEL_TYPE_DATA32F: u32 = 18874652;
pub const PYLON_PIXEL_TYPE_DATA64: u32 = 20971805;
pub const PYLON_PIXEL_TYPE_DATA64S: u32 = 20971806;
pub const PYLON_PIXEL_TYPE_DATA64F: u32 = 20971807;
#[repr(C)]
#[derive(Debug)]
pub struct PylonDeviceInfo {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug)]
pub struct PylonCamera {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug)]
pub struct PylonGrabResult {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug)]
pub struct PylonConverter {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug)]
pub struct PylonImage {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug)]
pub struct PylonNodeMap {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug)]
pub struct PylonNode {
    _unused: [u8; 0],
}
impl PylonStatus {
    pub const PYLON_OK: PylonStatus = PylonStatus(0);
    pub const PYLON_ERROR_GENERIC: PylonStatus = PylonStatus(1);
    pub const PYLON_ERROR_BAD_ALLOC: PylonStatus = PylonStatus(2);
    pub const PYLON_ERROR_INVALID_ARGUMENT: PylonStatus = PylonStatus(3);
    pub const PYLON_ERROR_OUT_OF_RANGE: PylonStatus = PylonStatus(4);
    pub const PYLON_ERROR_PROPERTY: PylonStatus = PylonStatus(5);
    pub const PYLON_ERROR_RUNTIME: PylonStatus = PylonStatus(6);
    pub const PYLON_ERROR_LOGICAL: PylonStatus = PylonStatus(7);
    pub const PYLON_ERROR_ACCESS: PylonStatus = PylonStatus(8);
    pub const PYLON_ERROR_TIMEOUT: PylonStatus = PylonStatus(9);
    pub const PYLON_ERROR_DYNAMIC_CAST: PylonStatus = PylonStatus(10);
    pub const PYLON_ERROR_UNKNOWN: PylonStatus = PylonStatus(11);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct PylonStatus(pub i32);
pub type PylonStringCallback = ::std::option::Option<
    unsafe extern "C" fn(
        ctx: *mut ::std::os::raw::c_void,
        data: *const ::std::os::raw::c_char,
        len: usize,
    ),
>;
pub type PylonNodeCallback = ::std::option::Option<
    unsafe extern "C" fn(ctx: *mut ::std::os::raw::c_void, node: *mut PylonNode),
>;
pub type PylonDeviceInfoCallback = ::std::option::Option<
    unsafe extern "C" fn(ctx: *mut ::std::os::raw::c_void, info: *mut PylonDeviceInfo),
>;
unsafe extern "C" {
    pub fn pylon_last_error() -> *const ::std::os::raw::c_char;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct PylonVersion {
    pub major: u32,
    pub minor: u32,
    pub subminor: u32,
    pub build: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PylonVersion"][::std::mem::size_of::<PylonVersion>() - 16usize];
    ["Alignment of PylonVersion"][::std::mem::align_of::<PylonVersion>() - 4usize];
    ["Offset of field: PylonVersion::major"][::std::mem::offset_of!(PylonVersion, major) - 0usize];
    ["Offset of field: PylonVersion::minor"][::std::mem::offset_of!(PylonVersion, minor) - 4usize];
    ["Offset of field: PylonVersion::subminor"]
        [::std::mem::offset_of!(PylonVersion, subminor) - 8usize];
    ["Offset of field: PylonVersion::build"][::std::mem::offset_of!(PylonVersion, build) - 12usize];
};
unsafe extern "C" {
    pub fn pylon_initialize() -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_terminate() -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_version() -> PylonVersion;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PylonPixelTypeInfo {
    pub name: *const ::std::os::raw::c_char,
    pub bits_per_pixel: u32,
    pub bit_depth: u32,
    pub samples_per_pixel: u32,
    pub plane_count: u32,
    pub is_mono: bool,
    pub is_bayer: bool,
    pub is_packed: bool,
    pub has_alpha: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PylonPixelTypeInfo"][::std::mem::size_of::<PylonPixelTypeInfo>() - 32usize];
    ["Alignment of PylonPixelTypeInfo"][::std::mem::align_of::<PylonPixelTypeInfo>() - 8usize];
    ["Offset of field: PylonPixelTypeInfo::name"]
        [::std::mem::offset_of!(PylonPixelTypeInfo, name) - 0usize];
    ["Offset of field: PylonPixelTypeInfo::bits_per_pixel"]
        [::std::mem::offset_of!(PylonPixelTypeInfo, bits_per_pixel) - 8usize];
    ["Offset of field: PylonPixelTypeInfo::bit_depth"]
        [::std::mem::offset_of!(PylonPixelTypeInfo, bit_depth) - 12usize];
    ["Offset of field: PylonPixelTypeInfo::samples_per_pixel"]
        [::std::mem::offset_of!(PylonPixelTypeInfo, samples_per_pixel) - 16usize];
    ["Offset of field: PylonPixelTypeInfo::plane_count"]
        [::std::mem::offset_of!(PylonPixelTypeInfo, plane_count) - 20usize];
    ["Offset of field: PylonPixelTypeInfo::is_mono"]
        [::std::mem::offset_of!(PylonPixelTypeInfo, is_mono) - 24usize];
    ["Offset of field: PylonPixelTypeInfo::is_bayer"]
        [::std::mem::offset_of!(PylonPixelTypeInfo, is_bayer) - 25usize];
    ["Offset of field: PylonPixelTypeInfo::is_packed"]
        [::std::mem::offset_of!(PylonPixelTypeInfo, is_packed) - 26usize];
    ["Offset of field: PylonPixelTypeInfo::has_alpha"]
        [::std::mem::offset_of!(PylonPixelTypeInfo, has_alpha) - 27usize];
};
impl Default for PylonPixelTypeInfo {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn pylon_pixel_type_info(pixel_type: u32, out: *mut PylonPixelTypeInfo) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_pixel_type_from_name(name: *const ::std::os::raw::c_char) -> u32;
}
unsafe extern "C" {
    pub fn pylon_pixel_type_stride(
        pixel_type: u32,
        width: u32,
        padding_x: usize,
        out: *mut usize,
    ) -> PylonStatus;
}
impl PylonImageOrientation {
    pub const PYLON_IMAGE_ORIENTATION_TOP_DOWN: PylonImageOrientation = PylonImageOrientation(0);
    pub const PYLON_IMAGE_ORIENTATION_BOTTOM_UP: PylonImageOrientation = PylonImageOrientation(1);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct PylonImageOrientation(pub i32);
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PylonImageView {
    pub buffer: *const ::std::os::raw::c_void,
    pub size: usize,
    pub pixel_type: u32,
    pub width: u32,
    pub height: u32,
    pub padding_x: usize,
    pub orientation: PylonImageOrientation,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PylonImageView"][::std::mem::size_of::<PylonImageView>() - 48usize];
    ["Alignment of PylonImageView"][::std::mem::align_of::<PylonImageView>() - 8usize];
    ["Offset of field: PylonImageView::buffer"]
        [::std::mem::offset_of!(PylonImageView, buffer) - 0usize];
    ["Offset of field: PylonImageView::size"]
        [::std::mem::offset_of!(PylonImageView, size) - 8usize];
    ["Offset of field: PylonImageView::pixel_type"]
        [::std::mem::offset_of!(PylonImageView, pixel_type) - 16usize];
    ["Offset of field: PylonImageView::width"]
        [::std::mem::offset_of!(PylonImageView, width) - 20usize];
    ["Offset of field: PylonImageView::height"]
        [::std::mem::offset_of!(PylonImageView, height) - 24usize];
    ["Offset of field: PylonImageView::padding_x"]
        [::std::mem::offset_of!(PylonImageView, padding_x) - 32usize];
    ["Offset of field: PylonImageView::orientation"]
        [::std::mem::offset_of!(PylonImageView, orientation) - 40usize];
};
impl Default for PylonImageView {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn pylon_device_info_create(out: *mut *mut PylonDeviceInfo) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_device_info_destroy(info: *mut PylonDeviceInfo);
}
unsafe extern "C" {
    pub fn pylon_device_info_get(
        info: *const PylonDeviceInfo,
        key: *const ::std::os::raw::c_char,
        cb: PylonStringCallback,
        ctx: *mut ::std::os::raw::c_void,
    ) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_device_info_set(
        info: *mut PylonDeviceInfo,
        key: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_device_info_keys(
        info: *const PylonDeviceInfo,
        cb: PylonStringCallback,
        ctx: *mut ::std::os::raw::c_void,
    ) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_enumerate_devices(
        filters: *const *const PylonDeviceInfo,
        filter_count: usize,
        cb: PylonDeviceInfoCallback,
        ctx: *mut ::std::os::raw::c_void,
    ) -> PylonStatus;
}
impl PylonNodeMapKind {
    pub const PYLON_NODE_MAP_DEVICE: PylonNodeMapKind = PylonNodeMapKind(0);
    pub const PYLON_NODE_MAP_TRANSPORT_LAYER: PylonNodeMapKind = PylonNodeMapKind(1);
    pub const PYLON_NODE_MAP_STREAM_GRABBER: PylonNodeMapKind = PylonNodeMapKind(2);
    pub const PYLON_NODE_MAP_EVENT_GRABBER: PylonNodeMapKind = PylonNodeMapKind(3);
    pub const PYLON_NODE_MAP_INSTANT_CAMERA: PylonNodeMapKind = PylonNodeMapKind(4);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct PylonNodeMapKind(pub i32);
impl PylonConfiguration {
    pub const PYLON_CONFIGURATION_NONE: PylonConfiguration = PylonConfiguration(0);
    pub const PYLON_CONFIGURATION_ACQUIRE_CONTINUOUS: PylonConfiguration = PylonConfiguration(1);
    pub const PYLON_CONFIGURATION_ACQUIRE_SINGLE_FRAME: PylonConfiguration = PylonConfiguration(2);
    pub const PYLON_CONFIGURATION_SOFTWARE_TRIGGER: PylonConfiguration = PylonConfiguration(3);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct PylonConfiguration(pub i32);
impl PylonGrabStrategy {
    pub const PYLON_GRAB_STRATEGY_ONE_BY_ONE: PylonGrabStrategy = PylonGrabStrategy(0);
    pub const PYLON_GRAB_STRATEGY_LATEST_IMAGE_ONLY: PylonGrabStrategy = PylonGrabStrategy(1);
    pub const PYLON_GRAB_STRATEGY_LATEST_IMAGES: PylonGrabStrategy = PylonGrabStrategy(2);
    pub const PYLON_GRAB_STRATEGY_UPCOMING_IMAGE: PylonGrabStrategy = PylonGrabStrategy(3);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct PylonGrabStrategy(pub i32);
unsafe extern "C" {
    pub fn pylon_camera_create(
        info: *const PylonDeviceInfo,
        out: *mut *mut PylonCamera,
    ) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_camera_destroy(camera: *mut PylonCamera);
}
unsafe extern "C" {
    pub fn pylon_camera_device_info(
        camera: *const PylonCamera,
        out: *mut *mut PylonDeviceInfo,
    ) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_camera_open(camera: *mut PylonCamera) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_camera_close(camera: *mut PylonCamera);
}
unsafe extern "C" {
    pub fn pylon_camera_is_open(camera: *const PylonCamera) -> bool;
}
unsafe extern "C" {
    pub fn pylon_camera_is_device_removed(camera: *const PylonCamera) -> bool;
}
unsafe extern "C" {
    pub fn pylon_camera_node_map(
        camera: *mut PylonCamera,
        kind: PylonNodeMapKind,
        out: *mut *mut PylonNodeMap,
    ) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_camera_set_configuration(
        camera: *mut PylonCamera,
        configuration: PylonConfiguration,
    ) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_camera_start_grabbing(
        camera: *mut PylonCamera,
        strategy: PylonGrabStrategy,
        max_images: usize,
    ) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_camera_stop_grabbing(camera: *mut PylonCamera);
}
unsafe extern "C" {
    pub fn pylon_camera_is_grabbing(camera: *const PylonCamera) -> bool;
}
unsafe extern "C" {
    pub fn pylon_camera_retrieve_result(
        camera: *mut PylonCamera,
        timeout_ms: u32,
        out: *mut *mut PylonGrabResult,
    ) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_camera_grab_one(
        camera: *mut PylonCamera,
        timeout_ms: u32,
        out: *mut *mut PylonGrabResult,
    ) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_camera_can_wait_for_frame_trigger_ready(
        camera: *const PylonCamera,
        out: *mut bool,
    ) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_camera_wait_for_frame_trigger_ready(
        camera: *mut PylonCamera,
        timeout_ms: u32,
        out: *mut bool,
    ) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_camera_execute_software_trigger(camera: *mut PylonCamera) -> PylonStatus;
}
impl PylonPayloadType {
    pub const PYLON_PAYLOAD_TYPE_UNDEFINED: PylonPayloadType = PylonPayloadType(-1);
    pub const PYLON_PAYLOAD_TYPE_IMAGE: PylonPayloadType = PylonPayloadType(0);
    pub const PYLON_PAYLOAD_TYPE_RAW_DATA: PylonPayloadType = PylonPayloadType(1);
    pub const PYLON_PAYLOAD_TYPE_FILE: PylonPayloadType = PylonPayloadType(2);
    pub const PYLON_PAYLOAD_TYPE_CHUNK_DATA: PylonPayloadType = PylonPayloadType(3);
    pub const PYLON_PAYLOAD_TYPE_GEN_DC: PylonPayloadType = PylonPayloadType(4);
    pub const PYLON_PAYLOAD_TYPE_DEVICE_SPECIFIC: PylonPayloadType = PylonPayloadType(32768);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct PylonPayloadType(pub i32);
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PylonGrabResultInfo {
    pub succeeded: bool,
    pub error_code: u32,
    pub payload_type: PylonPayloadType,
    pub payload: *const ::std::os::raw::c_void,
    pub payload_size: usize,
    pub image: PylonImageView,
    pub offset_x: u32,
    pub offset_y: u32,
    pub padding_y: u32,
    pub block_id: u64,
    pub timestamp: u64,
    pub id: i64,
    pub image_number: i64,
    pub skipped_images: i64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PylonGrabResultInfo"][::std::mem::size_of::<PylonGrabResultInfo>() - 136usize];
    ["Alignment of PylonGrabResultInfo"][::std::mem::align_of::<PylonGrabResultInfo>() - 8usize];
    ["Offset of field: PylonGrabResultInfo::succeeded"]
        [::std::mem::offset_of!(PylonGrabResultInfo, succeeded) - 0usize];
    ["Offset of field: PylonGrabResultInfo::error_code"]
        [::std::mem::offset_of!(PylonGrabResultInfo, error_code) - 4usize];
    ["Offset of field: PylonGrabResultInfo::payload_type"]
        [::std::mem::offset_of!(PylonGrabResultInfo, payload_type) - 8usize];
    ["Offset of field: PylonGrabResultInfo::payload"]
        [::std::mem::offset_of!(PylonGrabResultInfo, payload) - 16usize];
    ["Offset of field: PylonGrabResultInfo::payload_size"]
        [::std::mem::offset_of!(PylonGrabResultInfo, payload_size) - 24usize];
    ["Offset of field: PylonGrabResultInfo::image"]
        [::std::mem::offset_of!(PylonGrabResultInfo, image) - 32usize];
    ["Offset of field: PylonGrabResultInfo::offset_x"]
        [::std::mem::offset_of!(PylonGrabResultInfo, offset_x) - 80usize];
    ["Offset of field: PylonGrabResultInfo::offset_y"]
        [::std::mem::offset_of!(PylonGrabResultInfo, offset_y) - 84usize];
    ["Offset of field: PylonGrabResultInfo::padding_y"]
        [::std::mem::offset_of!(PylonGrabResultInfo, padding_y) - 88usize];
    ["Offset of field: PylonGrabResultInfo::block_id"]
        [::std::mem::offset_of!(PylonGrabResultInfo, block_id) - 96usize];
    ["Offset of field: PylonGrabResultInfo::timestamp"]
        [::std::mem::offset_of!(PylonGrabResultInfo, timestamp) - 104usize];
    ["Offset of field: PylonGrabResultInfo::id"]
        [::std::mem::offset_of!(PylonGrabResultInfo, id) - 112usize];
    ["Offset of field: PylonGrabResultInfo::image_number"]
        [::std::mem::offset_of!(PylonGrabResultInfo, image_number) - 120usize];
    ["Offset of field: PylonGrabResultInfo::skipped_images"]
        [::std::mem::offset_of!(PylonGrabResultInfo, skipped_images) - 128usize];
};
impl Default for PylonGrabResultInfo {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn pylon_grab_result_destroy(result: *mut PylonGrabResult);
}
unsafe extern "C" {
    pub fn pylon_grab_result_info(
        result: *const PylonGrabResult,
        out: *mut PylonGrabResultInfo,
    ) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_grab_result_error_description(
        result: *const PylonGrabResult,
        cb: PylonStringCallback,
        ctx: *mut ::std::os::raw::c_void,
    ) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_grab_result_chunk_node_map(
        result: *const PylonGrabResult,
        out: *mut *mut PylonNodeMap,
    ) -> PylonStatus;
}
impl PylonNodeType {
    pub const PYLON_NODE_TYPE_VALUE: PylonNodeType = PylonNodeType(0);
    pub const PYLON_NODE_TYPE_BASE: PylonNodeType = PylonNodeType(1);
    pub const PYLON_NODE_TYPE_INTEGER: PylonNodeType = PylonNodeType(2);
    pub const PYLON_NODE_TYPE_BOOLEAN: PylonNodeType = PylonNodeType(3);
    pub const PYLON_NODE_TYPE_COMMAND: PylonNodeType = PylonNodeType(4);
    pub const PYLON_NODE_TYPE_FLOAT: PylonNodeType = PylonNodeType(5);
    pub const PYLON_NODE_TYPE_STRING: PylonNodeType = PylonNodeType(6);
    pub const PYLON_NODE_TYPE_REGISTER: PylonNodeType = PylonNodeType(7);
    pub const PYLON_NODE_TYPE_CATEGORY: PylonNodeType = PylonNodeType(8);
    pub const PYLON_NODE_TYPE_ENUMERATION: PylonNodeType = PylonNodeType(9);
    pub const PYLON_NODE_TYPE_ENUM_ENTRY: PylonNodeType = PylonNodeType(10);
    pub const PYLON_NODE_TYPE_PORT: PylonNodeType = PylonNodeType(11);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct PylonNodeType(pub i32);
impl PylonAccessMode {
    pub const PYLON_ACCESS_MODE_NI: PylonAccessMode = PylonAccessMode(0);
    pub const PYLON_ACCESS_MODE_NA: PylonAccessMode = PylonAccessMode(1);
    pub const PYLON_ACCESS_MODE_WO: PylonAccessMode = PylonAccessMode(2);
    pub const PYLON_ACCESS_MODE_RO: PylonAccessMode = PylonAccessMode(3);
    pub const PYLON_ACCESS_MODE_RW: PylonAccessMode = PylonAccessMode(4);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct PylonAccessMode(pub i32);
impl PylonNodeText {
    pub const PYLON_NODE_TEXT_NAME: PylonNodeText = PylonNodeText(0);
    pub const PYLON_NODE_TEXT_DISPLAY_NAME: PylonNodeText = PylonNodeText(1);
    pub const PYLON_NODE_TEXT_TOOL_TIP: PylonNodeText = PylonNodeText(2);
    pub const PYLON_NODE_TEXT_DESCRIPTION: PylonNodeText = PylonNodeText(3);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct PylonNodeText(pub i32);
unsafe extern "C" {
    pub fn pylon_node_map_node(
        map: *mut PylonNodeMap,
        name: *const ::std::os::raw::c_char,
        out: *mut *mut PylonNode,
    ) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_node_map_load(
        map: *mut PylonNodeMap,
        features: *const ::std::os::raw::c_char,
        validate: bool,
    ) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_node_map_save(
        map: *mut PylonNodeMap,
        cb: PylonStringCallback,
        ctx: *mut ::std::os::raw::c_void,
    ) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_node_type(node: *mut PylonNode, out: *mut PylonNodeType) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_node_access_mode(node: *mut PylonNode, out: *mut PylonAccessMode) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_node_text(
        node: *mut PylonNode,
        text: PylonNodeText,
        cb: PylonStringCallback,
        ctx: *mut ::std::os::raw::c_void,
    ) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_node_register_callback(
        node: *mut PylonNode,
        cb: PylonNodeCallback,
        ctx: *mut ::std::os::raw::c_void,
        out: *mut isize,
    ) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_node_deregister_callback(registration: isize) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_value_to_string(
        node: *mut PylonNode,
        cb: PylonStringCallback,
        ctx: *mut ::std::os::raw::c_void,
    ) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_value_from_string(
        node: *mut PylonNode,
        value: *const ::std::os::raw::c_char,
    ) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_integer_get(node: *mut PylonNode, out: *mut i64) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_integer_set(node: *mut PylonNode, value: i64) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_integer_range(
        node: *mut PylonNode,
        min: *mut i64,
        max: *mut i64,
        inc: *mut i64,
    ) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_float_get(node: *mut PylonNode, out: *mut f64) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_float_set(node: *mut PylonNode, value: f64) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_float_range(
        node: *mut PylonNode,
        min: *mut f64,
        max: *mut f64,
        inc: *mut f64,
    ) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_boolean_get(node: *mut PylonNode, out: *mut bool) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_boolean_set(node: *mut PylonNode, value: bool) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_command_execute(node: *mut PylonNode) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_command_is_done(node: *mut PylonNode, out: *mut bool) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_enumeration_entries(
        node: *mut PylonNode,
        cb: PylonNodeCallback,
        ctx: *mut ::std::os::raw::c_void,
    ) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_enum_entry_symbolic(
        node: *mut PylonNode,
        cb: PylonStringCallback,
        ctx: *mut ::std::os::raw::c_void,
    ) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_category_features(
        node: *mut PylonNode,
        cb: PylonNodeCallback,
        ctx: *mut ::std::os::raw::c_void,
    ) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_image_create(out: *mut *mut PylonImage) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_image_destroy(image: *mut PylonImage);
}
unsafe extern "C" {
    pub fn pylon_image_view(image: *const PylonImage) -> PylonImageView;
}
unsafe extern "C" {
    pub fn pylon_converter_create(out: *mut *mut PylonConverter) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_converter_destroy(converter: *mut PylonConverter);
}
unsafe extern "C" {
    pub fn pylon_converter_node_map(converter: *mut PylonConverter) -> *mut PylonNodeMap;
}
unsafe extern "C" {
    pub fn pylon_converter_set_output_pixel_type(
        converter: *mut PylonConverter,
        pixel_type: u32,
    ) -> PylonStatus;
}
unsafe extern "C" {
    pub fn pylon_converter_has_destination_format(
        converter: *const PylonConverter,
        source: *const PylonImageView,
    ) -> bool;
}
unsafe extern "C" {
    pub fn pylon_converter_convert(
        converter: *mut PylonConverter,
        destination: *mut PylonImage,
        source: *const PylonImageView,
    ) -> PylonStatus;
}
